### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dmblock** [WaterdogPE/WaterdogPE#249] opened 2022-12-23 15:50 UTC
**Describe the bug**
Met a problem in joining server.
How to fix this problem?

**To Reproduce**
1. Join server

**Expected behavior**
java.util.concurrent.TimeoutException

**Screenshots**
![Screenshot_20221223-232645](https://user-images.githubusercontent.com/62496819/209362401-533c533b-3ff8-443b-882e-7aad3891f05f.png)

**Platform Information:**
 - Game Platform: Android and Windows
 - Game (Client) Version: v1.19.50
 - Server OS: Ubuntu 22
 - Java Version Java17 (docker)azul/zulu-openjdk-alpine:17-latest
 - Server Deployment Method: Docker in Mcsmanager

**Additional context**

**Comment by xxFLORII** [comment] 2022-12-23 17:03
Hey, please check if the server you want to connect to is online, if so check the IP/port you entered for the server in the Waterdog config. The error only means that the server you want to connect to is not available/online.

**Comment by Alemiz112** [comment] 2023-01-13 19:28
Duplicate of #178

**Closed by Alemiz112** 2023-01-13 19:28 UTC
Labels: bug, unconfirmed
