### ISSUE TITLE
ProxyProtocol support

### ISSUE THREAD

**Issue by Szczurowsky** [WaterdogPE/WaterdogPE#247] opened 2022-12-18 21:51 UTC
**Is your feature request related to a problem? Please describe.**
We all are aware of problem with network attacks. Most of server owners will use/create DDoS protection solution which are reverse proxy's. Key thing is to pass client IP and use it instead of reverse proxy IP, for this crucial thing is to support Proxy Protocol which is widely used in this case.

**Describe the solution you'd like**
Implementing config option to enable Proxy Protocol support and obviously implement handling it in a code

**Comment by TobiasGrether** [comment] 2024-01-16 20:27
Duplicate of #212

**Closed by TobiasGrether** 2024-01-16 20:27 UTC
Labels: enhancement
