### ISSUE TITLE
Education edition items on PM4

### ISSUE THREAD

**Issue by TheDataLion** [WaterdogPE/WaterdogPE#80] opened 2021-04-11 01:05 UTC
So in Pocketmine 4.0 they added education edition items.
But this causes the client to crash when looking for those in your inventory.
At the Discord I asked for help and someone tried to figure out what could cause the issue.

He thinks it has something to do with the item palette, but didn't see any way that Waterdog managed that.

![Element Items](https://media.discordapp.net/attachments/767331674245431306/830570859072192542/unknown.png)

https://user-images.githubusercontent.com/34657342/114288606-d9bdab00-9a71-11eb-8dd6-3865d1717878.mp4

**Comment by Alemiz112** [comment] 2021-04-11 11:48
Hello, thank you for opening the issue! I will look into this soon.

**Comment by StijnJ07** [comment] 2021-04-29 22:10
> Hello, thank you for opening the issue! I will look into this soon.

Any progress?

**Comment by Alemiz112** [comment] 2021-04-30 10:05
Hello, yes the issue is now fixed.

It turned out that client was crashing because it didn't load required resources for education items. This can happen when you have enabled resource packs, `enable_packs`, option in proxy config.

I have adjusted proxy behavior and you can solve this issue by two different ways:
- If you don't require require packs to be applied, disable `enable_packs` and requested packs from initial downstream will be used.
- If you plan to use resource packs, enable `enable_edu_features` option and proxy will know to request additional education resources. **This option will only work since master build 64.** 

**I would recommend you to use the second option if you don't know what exactly will first one do.*

**Closed** 2021-04-30 14:49 UTC
Labels: bug, pmmp
